//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Cliente.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgendarAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemarcarAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaAgendamentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GerarAtendimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirAtendimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarAtendimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAtendimentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarConvenioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InativarConvenioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarConveniosOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarPrestadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback InativarPrestadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarPrestadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaPrestadoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdicionarProcedimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtuaizarProcedimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarProcedimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirTipoConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InativarTipoConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTipoConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarUsuariosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Cliente.Properties.Settings.Default.Cliente_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgendarAgendamentoCompletedEventHandler AgendarAgendamentoCompleted;
        
        /// <remarks/>
        public event RemarcarAgendamentoCompletedEventHandler RemarcarAgendamentoCompleted;
        
        /// <remarks/>
        public event ExcluirAgendamentoCompletedEventHandler ExcluirAgendamentoCompleted;
        
        /// <remarks/>
        public event ListaAgendamentosCompletedEventHandler ListaAgendamentosCompleted;
        
        /// <remarks/>
        public event GerarAtendimentoCompletedEventHandler GerarAtendimentoCompleted;
        
        /// <remarks/>
        public event ExcluirAtendimentoCompletedEventHandler ExcluirAtendimentoCompleted;
        
        /// <remarks/>
        public event AtualizarAtendimentoCompletedEventHandler AtualizarAtendimentoCompleted;
        
        /// <remarks/>
        public event ListarAtendimentosCompletedEventHandler ListarAtendimentosCompleted;
        
        /// <remarks/>
        public event CadastrarConvenioCompletedEventHandler CadastrarConvenioCompleted;
        
        /// <remarks/>
        public event InativarConvenioCompletedEventHandler InativarConvenioCompleted;
        
        /// <remarks/>
        public event ListarConveniosCompletedEventHandler ListarConveniosCompleted;
        
        /// <remarks/>
        public event CadastrarPacienteCompletedEventHandler CadastrarPacienteCompleted;
        
        /// <remarks/>
        public event AlterarPacienteCompletedEventHandler AlterarPacienteCompleted;
        
        /// <remarks/>
        public event ListaPacienteCompletedEventHandler ListaPacienteCompleted;
        
        /// <remarks/>
        public event CadastrarPrestadorCompletedEventHandler CadastrarPrestadorCompleted;
        
        /// <remarks/>
        public event InativarPrestadorCompletedEventHandler InativarPrestadorCompleted;
        
        /// <remarks/>
        public event AtualizarPrestadorCompletedEventHandler AtualizarPrestadorCompleted;
        
        /// <remarks/>
        public event ListaPrestadoresCompletedEventHandler ListaPrestadoresCompleted;
        
        /// <remarks/>
        public event AdicionarProcedimentoCompletedEventHandler AdicionarProcedimentoCompleted;
        
        /// <remarks/>
        public event AtuaizarProcedimentoCompletedEventHandler AtuaizarProcedimentoCompleted;
        
        /// <remarks/>
        public event ListarProcedimentoCompletedEventHandler ListarProcedimentoCompleted;
        
        /// <remarks/>
        public event InserirTipoConsultaCompletedEventHandler InserirTipoConsultaCompleted;
        
        /// <remarks/>
        public event InativarTipoConsultaCompletedEventHandler InativarTipoConsultaCompleted;
        
        /// <remarks/>
        public event ListarTipoConsultaCompletedEventHandler ListarTipoConsultaCompleted;
        
        /// <remarks/>
        public event CadastrarUsuarioCompletedEventHandler CadastrarUsuarioCompleted;
        
        /// <remarks/>
        public event AlterarUsuarioCompletedEventHandler AlterarUsuarioCompleted;
        
        /// <remarks/>
        public event ListarUsuariosCompletedEventHandler ListarUsuariosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AgendarAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgendarAgendamento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Agendamento agendamento) {
            this.Invoke("AgendarAgendamento", new object[] {
                        agendamento});
        }
        
        /// <remarks/>
        public void AgendarAgendamentoAsync(Agendamento agendamento) {
            this.AgendarAgendamentoAsync(agendamento, null);
        }
        
        /// <remarks/>
        public void AgendarAgendamentoAsync(Agendamento agendamento, object userState) {
            if ((this.AgendarAgendamentoOperationCompleted == null)) {
                this.AgendarAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgendarAgendamentoOperationCompleted);
            }
            this.InvokeAsync("AgendarAgendamento", new object[] {
                        agendamento}, this.AgendarAgendamentoOperationCompleted, userState);
        }
        
        private void OnAgendarAgendamentoOperationCompleted(object arg) {
            if ((this.AgendarAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgendarAgendamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RemarcarAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemarcarAgendamento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Agendamento agendamento) {
            this.Invoke("RemarcarAgendamento", new object[] {
                        agendamento});
        }
        
        /// <remarks/>
        public void RemarcarAgendamentoAsync(Agendamento agendamento) {
            this.RemarcarAgendamentoAsync(agendamento, null);
        }
        
        /// <remarks/>
        public void RemarcarAgendamentoAsync(Agendamento agendamento, object userState) {
            if ((this.RemarcarAgendamentoOperationCompleted == null)) {
                this.RemarcarAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemarcarAgendamentoOperationCompleted);
            }
            this.InvokeAsync("RemarcarAgendamento", new object[] {
                        agendamento}, this.RemarcarAgendamentoOperationCompleted, userState);
        }
        
        private void OnRemarcarAgendamentoOperationCompleted(object arg) {
            if ((this.RemarcarAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemarcarAgendamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirAgendamento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Agendamento agendamento) {
            this.Invoke("ExcluirAgendamento", new object[] {
                        agendamento});
        }
        
        /// <remarks/>
        public void ExcluirAgendamentoAsync(Agendamento agendamento) {
            this.ExcluirAgendamentoAsync(agendamento, null);
        }
        
        /// <remarks/>
        public void ExcluirAgendamentoAsync(Agendamento agendamento, object userState) {
            if ((this.ExcluirAgendamentoOperationCompleted == null)) {
                this.ExcluirAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirAgendamentoOperationCompleted);
            }
            this.InvokeAsync("ExcluirAgendamento", new object[] {
                        agendamento}, this.ExcluirAgendamentoOperationCompleted, userState);
        }
        
        private void OnExcluirAgendamentoOperationCompleted(object arg) {
            if ((this.ExcluirAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirAgendamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListaAgendamentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Agendamento[] ListaAgendamentos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Agendamento agendamento) {
            object[] results = this.Invoke("ListaAgendamentos", new object[] {
                        agendamento});
            return ((Agendamento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaAgendamentosAsync(Agendamento agendamento) {
            this.ListaAgendamentosAsync(agendamento, null);
        }
        
        /// <remarks/>
        public void ListaAgendamentosAsync(Agendamento agendamento, object userState) {
            if ((this.ListaAgendamentosOperationCompleted == null)) {
                this.ListaAgendamentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaAgendamentosOperationCompleted);
            }
            this.InvokeAsync("ListaAgendamentos", new object[] {
                        agendamento}, this.ListaAgendamentosOperationCompleted, userState);
        }
        
        private void OnListaAgendamentosOperationCompleted(object arg) {
            if ((this.ListaAgendamentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaAgendamentosCompleted(this, new ListaAgendamentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GerarAtendimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GerarAtendimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Atendimento atendimento) {
            this.Invoke("GerarAtendimento", new object[] {
                        atendimento});
        }
        
        /// <remarks/>
        public void GerarAtendimentoAsync(Atendimento atendimento) {
            this.GerarAtendimentoAsync(atendimento, null);
        }
        
        /// <remarks/>
        public void GerarAtendimentoAsync(Atendimento atendimento, object userState) {
            if ((this.GerarAtendimentoOperationCompleted == null)) {
                this.GerarAtendimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGerarAtendimentoOperationCompleted);
            }
            this.InvokeAsync("GerarAtendimento", new object[] {
                        atendimento}, this.GerarAtendimentoOperationCompleted, userState);
        }
        
        private void OnGerarAtendimentoOperationCompleted(object arg) {
            if ((this.GerarAtendimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GerarAtendimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirAtendimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirAtendimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Atendimento atendimento) {
            this.Invoke("ExcluirAtendimento", new object[] {
                        atendimento});
        }
        
        /// <remarks/>
        public void ExcluirAtendimentoAsync(Atendimento atendimento) {
            this.ExcluirAtendimentoAsync(atendimento, null);
        }
        
        /// <remarks/>
        public void ExcluirAtendimentoAsync(Atendimento atendimento, object userState) {
            if ((this.ExcluirAtendimentoOperationCompleted == null)) {
                this.ExcluirAtendimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirAtendimentoOperationCompleted);
            }
            this.InvokeAsync("ExcluirAtendimento", new object[] {
                        atendimento}, this.ExcluirAtendimentoOperationCompleted, userState);
        }
        
        private void OnExcluirAtendimentoOperationCompleted(object arg) {
            if ((this.ExcluirAtendimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirAtendimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AtualizarAtendimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtualizarAtendimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Atendimento atendimento) {
            this.Invoke("AtualizarAtendimento", new object[] {
                        atendimento});
        }
        
        /// <remarks/>
        public void AtualizarAtendimentoAsync(Atendimento atendimento) {
            this.AtualizarAtendimentoAsync(atendimento, null);
        }
        
        /// <remarks/>
        public void AtualizarAtendimentoAsync(Atendimento atendimento, object userState) {
            if ((this.AtualizarAtendimentoOperationCompleted == null)) {
                this.AtualizarAtendimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarAtendimentoOperationCompleted);
            }
            this.InvokeAsync("AtualizarAtendimento", new object[] {
                        atendimento}, this.AtualizarAtendimentoOperationCompleted, userState);
        }
        
        private void OnAtualizarAtendimentoOperationCompleted(object arg) {
            if ((this.AtualizarAtendimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarAtendimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarAtendimentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Atendimento[] ListarAtendimentos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Atendimento atendimento) {
            object[] results = this.Invoke("ListarAtendimentos", new object[] {
                        atendimento});
            return ((Atendimento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAtendimentosAsync(Atendimento atendimento) {
            this.ListarAtendimentosAsync(atendimento, null);
        }
        
        /// <remarks/>
        public void ListarAtendimentosAsync(Atendimento atendimento, object userState) {
            if ((this.ListarAtendimentosOperationCompleted == null)) {
                this.ListarAtendimentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAtendimentosOperationCompleted);
            }
            this.InvokeAsync("ListarAtendimentos", new object[] {
                        atendimento}, this.ListarAtendimentosOperationCompleted, userState);
        }
        
        private void OnListarAtendimentosOperationCompleted(object arg) {
            if ((this.ListarAtendimentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAtendimentosCompleted(this, new ListarAtendimentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarConvenio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarConvenio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Convenio convenio) {
            this.Invoke("CadastrarConvenio", new object[] {
                        convenio});
        }
        
        /// <remarks/>
        public void CadastrarConvenioAsync(Convenio convenio) {
            this.CadastrarConvenioAsync(convenio, null);
        }
        
        /// <remarks/>
        public void CadastrarConvenioAsync(Convenio convenio, object userState) {
            if ((this.CadastrarConvenioOperationCompleted == null)) {
                this.CadastrarConvenioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarConvenioOperationCompleted);
            }
            this.InvokeAsync("CadastrarConvenio", new object[] {
                        convenio}, this.CadastrarConvenioOperationCompleted, userState);
        }
        
        private void OnCadastrarConvenioOperationCompleted(object arg) {
            if ((this.CadastrarConvenioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarConvenioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InativarConvenio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InativarConvenio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Convenio convenio) {
            this.Invoke("InativarConvenio", new object[] {
                        convenio});
        }
        
        /// <remarks/>
        public void InativarConvenioAsync(Convenio convenio) {
            this.InativarConvenioAsync(convenio, null);
        }
        
        /// <remarks/>
        public void InativarConvenioAsync(Convenio convenio, object userState) {
            if ((this.InativarConvenioOperationCompleted == null)) {
                this.InativarConvenioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInativarConvenioOperationCompleted);
            }
            this.InvokeAsync("InativarConvenio", new object[] {
                        convenio}, this.InativarConvenioOperationCompleted, userState);
        }
        
        private void OnInativarConvenioOperationCompleted(object arg) {
            if ((this.InativarConvenioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InativarConvenioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarConvenios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Convenio[] ListarConvenios([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Convenio filtro) {
            object[] results = this.Invoke("ListarConvenios", new object[] {
                        filtro});
            return ((Convenio[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarConveniosAsync(Convenio filtro) {
            this.ListarConveniosAsync(filtro, null);
        }
        
        /// <remarks/>
        public void ListarConveniosAsync(Convenio filtro, object userState) {
            if ((this.ListarConveniosOperationCompleted == null)) {
                this.ListarConveniosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarConveniosOperationCompleted);
            }
            this.InvokeAsync("ListarConvenios", new object[] {
                        filtro}, this.ListarConveniosOperationCompleted, userState);
        }
        
        private void OnListarConveniosOperationCompleted(object arg) {
            if ((this.ListarConveniosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarConveniosCompleted(this, new ListarConveniosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarPaciente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Paciente paciente) {
            this.Invoke("CadastrarPaciente", new object[] {
                        paciente});
        }
        
        /// <remarks/>
        public void CadastrarPacienteAsync(Paciente paciente) {
            this.CadastrarPacienteAsync(paciente, null);
        }
        
        /// <remarks/>
        public void CadastrarPacienteAsync(Paciente paciente, object userState) {
            if ((this.CadastrarPacienteOperationCompleted == null)) {
                this.CadastrarPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarPacienteOperationCompleted);
            }
            this.InvokeAsync("CadastrarPaciente", new object[] {
                        paciente}, this.CadastrarPacienteOperationCompleted, userState);
        }
        
        private void OnCadastrarPacienteOperationCompleted(object arg) {
            if ((this.CadastrarPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarPacienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarPaciente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Paciente paciente) {
            this.Invoke("AlterarPaciente", new object[] {
                        paciente});
        }
        
        /// <remarks/>
        public void AlterarPacienteAsync(Paciente paciente) {
            this.AlterarPacienteAsync(paciente, null);
        }
        
        /// <remarks/>
        public void AlterarPacienteAsync(Paciente paciente, object userState) {
            if ((this.AlterarPacienteOperationCompleted == null)) {
                this.AlterarPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarPacienteOperationCompleted);
            }
            this.InvokeAsync("AlterarPaciente", new object[] {
                        paciente}, this.AlterarPacienteOperationCompleted, userState);
        }
        
        private void OnAlterarPacienteOperationCompleted(object arg) {
            if ((this.AlterarPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarPacienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListaPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Paciente[] ListaPaciente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Paciente filtro) {
            object[] results = this.Invoke("ListaPaciente", new object[] {
                        filtro});
            return ((Paciente[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaPacienteAsync(Paciente filtro) {
            this.ListaPacienteAsync(filtro, null);
        }
        
        /// <remarks/>
        public void ListaPacienteAsync(Paciente filtro, object userState) {
            if ((this.ListaPacienteOperationCompleted == null)) {
                this.ListaPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaPacienteOperationCompleted);
            }
            this.InvokeAsync("ListaPaciente", new object[] {
                        filtro}, this.ListaPacienteOperationCompleted, userState);
        }
        
        private void OnListaPacienteOperationCompleted(object arg) {
            if ((this.ListaPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaPacienteCompleted(this, new ListaPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarPrestador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarPrestador([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Prestador prestador) {
            this.Invoke("CadastrarPrestador", new object[] {
                        prestador});
        }
        
        /// <remarks/>
        public void CadastrarPrestadorAsync(Prestador prestador) {
            this.CadastrarPrestadorAsync(prestador, null);
        }
        
        /// <remarks/>
        public void CadastrarPrestadorAsync(Prestador prestador, object userState) {
            if ((this.CadastrarPrestadorOperationCompleted == null)) {
                this.CadastrarPrestadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarPrestadorOperationCompleted);
            }
            this.InvokeAsync("CadastrarPrestador", new object[] {
                        prestador}, this.CadastrarPrestadorOperationCompleted, userState);
        }
        
        private void OnCadastrarPrestadorOperationCompleted(object arg) {
            if ((this.CadastrarPrestadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarPrestadorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InativarPrestador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InativarPrestador([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Prestador prestador) {
            this.Invoke("InativarPrestador", new object[] {
                        prestador});
        }
        
        /// <remarks/>
        public void InativarPrestadorAsync(Prestador prestador) {
            this.InativarPrestadorAsync(prestador, null);
        }
        
        /// <remarks/>
        public void InativarPrestadorAsync(Prestador prestador, object userState) {
            if ((this.InativarPrestadorOperationCompleted == null)) {
                this.InativarPrestadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInativarPrestadorOperationCompleted);
            }
            this.InvokeAsync("InativarPrestador", new object[] {
                        prestador}, this.InativarPrestadorOperationCompleted, userState);
        }
        
        private void OnInativarPrestadorOperationCompleted(object arg) {
            if ((this.InativarPrestadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InativarPrestadorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AtualizarPrestador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtualizarPrestador([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Prestador prestador) {
            this.Invoke("AtualizarPrestador", new object[] {
                        prestador});
        }
        
        /// <remarks/>
        public void AtualizarPrestadorAsync(Prestador prestador) {
            this.AtualizarPrestadorAsync(prestador, null);
        }
        
        /// <remarks/>
        public void AtualizarPrestadorAsync(Prestador prestador, object userState) {
            if ((this.AtualizarPrestadorOperationCompleted == null)) {
                this.AtualizarPrestadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarPrestadorOperationCompleted);
            }
            this.InvokeAsync("AtualizarPrestador", new object[] {
                        prestador}, this.AtualizarPrestadorOperationCompleted, userState);
        }
        
        private void OnAtualizarPrestadorOperationCompleted(object arg) {
            if ((this.AtualizarPrestadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarPrestadorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListaPrestadores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Prestador[] ListaPrestadores([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Prestador filtro) {
            object[] results = this.Invoke("ListaPrestadores", new object[] {
                        filtro});
            return ((Prestador[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaPrestadoresAsync(Prestador filtro) {
            this.ListaPrestadoresAsync(filtro, null);
        }
        
        /// <remarks/>
        public void ListaPrestadoresAsync(Prestador filtro, object userState) {
            if ((this.ListaPrestadoresOperationCompleted == null)) {
                this.ListaPrestadoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaPrestadoresOperationCompleted);
            }
            this.InvokeAsync("ListaPrestadores", new object[] {
                        filtro}, this.ListaPrestadoresOperationCompleted, userState);
        }
        
        private void OnListaPrestadoresOperationCompleted(object arg) {
            if ((this.ListaPrestadoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaPrestadoresCompleted(this, new ListaPrestadoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AdicionarProcedimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AdicionarProcedimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Procedimento procedimento) {
            this.Invoke("AdicionarProcedimento", new object[] {
                        procedimento});
        }
        
        /// <remarks/>
        public void AdicionarProcedimentoAsync(Procedimento procedimento) {
            this.AdicionarProcedimentoAsync(procedimento, null);
        }
        
        /// <remarks/>
        public void AdicionarProcedimentoAsync(Procedimento procedimento, object userState) {
            if ((this.AdicionarProcedimentoOperationCompleted == null)) {
                this.AdicionarProcedimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdicionarProcedimentoOperationCompleted);
            }
            this.InvokeAsync("AdicionarProcedimento", new object[] {
                        procedimento}, this.AdicionarProcedimentoOperationCompleted, userState);
        }
        
        private void OnAdicionarProcedimentoOperationCompleted(object arg) {
            if ((this.AdicionarProcedimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdicionarProcedimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AtuaizarProcedimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtuaizarProcedimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Procedimento procedimento) {
            this.Invoke("AtuaizarProcedimento", new object[] {
                        procedimento});
        }
        
        /// <remarks/>
        public void AtuaizarProcedimentoAsync(Procedimento procedimento) {
            this.AtuaizarProcedimentoAsync(procedimento, null);
        }
        
        /// <remarks/>
        public void AtuaizarProcedimentoAsync(Procedimento procedimento, object userState) {
            if ((this.AtuaizarProcedimentoOperationCompleted == null)) {
                this.AtuaizarProcedimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtuaizarProcedimentoOperationCompleted);
            }
            this.InvokeAsync("AtuaizarProcedimento", new object[] {
                        procedimento}, this.AtuaizarProcedimentoOperationCompleted, userState);
        }
        
        private void OnAtuaizarProcedimentoOperationCompleted(object arg) {
            if ((this.AtuaizarProcedimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtuaizarProcedimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarProcedimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Procedimento[] ListarProcedimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Procedimento procedimento) {
            object[] results = this.Invoke("ListarProcedimento", new object[] {
                        procedimento});
            return ((Procedimento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarProcedimentoAsync(Procedimento procedimento) {
            this.ListarProcedimentoAsync(procedimento, null);
        }
        
        /// <remarks/>
        public void ListarProcedimentoAsync(Procedimento procedimento, object userState) {
            if ((this.ListarProcedimentoOperationCompleted == null)) {
                this.ListarProcedimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarProcedimentoOperationCompleted);
            }
            this.InvokeAsync("ListarProcedimento", new object[] {
                        procedimento}, this.ListarProcedimentoOperationCompleted, userState);
        }
        
        private void OnListarProcedimentoOperationCompleted(object arg) {
            if ((this.ListarProcedimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarProcedimentoCompleted(this, new ListarProcedimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirTipoConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirTipoConsulta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TipoConsulta tipoConsulta) {
            this.Invoke("InserirTipoConsulta", new object[] {
                        tipoConsulta});
        }
        
        /// <remarks/>
        public void InserirTipoConsultaAsync(TipoConsulta tipoConsulta) {
            this.InserirTipoConsultaAsync(tipoConsulta, null);
        }
        
        /// <remarks/>
        public void InserirTipoConsultaAsync(TipoConsulta tipoConsulta, object userState) {
            if ((this.InserirTipoConsultaOperationCompleted == null)) {
                this.InserirTipoConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirTipoConsultaOperationCompleted);
            }
            this.InvokeAsync("InserirTipoConsulta", new object[] {
                        tipoConsulta}, this.InserirTipoConsultaOperationCompleted, userState);
        }
        
        private void OnInserirTipoConsultaOperationCompleted(object arg) {
            if ((this.InserirTipoConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirTipoConsultaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InativarTipoConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InativarTipoConsulta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TipoConsulta tipoConsulta) {
            this.Invoke("InativarTipoConsulta", new object[] {
                        tipoConsulta});
        }
        
        /// <remarks/>
        public void InativarTipoConsultaAsync(TipoConsulta tipoConsulta) {
            this.InativarTipoConsultaAsync(tipoConsulta, null);
        }
        
        /// <remarks/>
        public void InativarTipoConsultaAsync(TipoConsulta tipoConsulta, object userState) {
            if ((this.InativarTipoConsultaOperationCompleted == null)) {
                this.InativarTipoConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInativarTipoConsultaOperationCompleted);
            }
            this.InvokeAsync("InativarTipoConsulta", new object[] {
                        tipoConsulta}, this.InativarTipoConsultaOperationCompleted, userState);
        }
        
        private void OnInativarTipoConsultaOperationCompleted(object arg) {
            if ((this.InativarTipoConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InativarTipoConsultaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarTipoConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public TipoConsulta[] ListarTipoConsulta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TipoConsulta filtro) {
            object[] results = this.Invoke("ListarTipoConsulta", new object[] {
                        filtro});
            return ((TipoConsulta[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTipoConsultaAsync(TipoConsulta filtro) {
            this.ListarTipoConsultaAsync(filtro, null);
        }
        
        /// <remarks/>
        public void ListarTipoConsultaAsync(TipoConsulta filtro, object userState) {
            if ((this.ListarTipoConsultaOperationCompleted == null)) {
                this.ListarTipoConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTipoConsultaOperationCompleted);
            }
            this.InvokeAsync("ListarTipoConsulta", new object[] {
                        filtro}, this.ListarTipoConsultaOperationCompleted, userState);
        }
        
        private void OnListarTipoConsultaOperationCompleted(object arg) {
            if ((this.ListarTipoConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTipoConsultaCompleted(this, new ListarTipoConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            this.Invoke("CadastrarUsuario", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void CadastrarUsuarioAsync(Usuario usuario) {
            this.CadastrarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void CadastrarUsuarioAsync(Usuario usuario, object userState) {
            if ((this.CadastrarUsuarioOperationCompleted == null)) {
                this.CadastrarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarUsuarioOperationCompleted);
            }
            this.InvokeAsync("CadastrarUsuario", new object[] {
                        usuario}, this.CadastrarUsuarioOperationCompleted, userState);
        }
        
        private void OnCadastrarUsuarioOperationCompleted(object arg) {
            if ((this.CadastrarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            this.Invoke("AlterarUsuario", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(Usuario usuario) {
            this.AlterarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(Usuario usuario, object userState) {
            if ((this.AlterarUsuarioOperationCompleted == null)) {
                this.AlterarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarUsuarioOperationCompleted);
            }
            this.InvokeAsync("AlterarUsuario", new object[] {
                        usuario}, this.AlterarUsuarioOperationCompleted, userState);
        }
        
        private void OnAlterarUsuarioOperationCompleted(object arg) {
            if ((this.AlterarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Usuario[] ListarUsuarios([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario filtro) {
            object[] results = this.Invoke("ListarUsuarios", new object[] {
                        filtro});
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarUsuariosAsync(Usuario filtro) {
            this.ListarUsuariosAsync(filtro, null);
        }
        
        /// <remarks/>
        public void ListarUsuariosAsync(Usuario filtro, object userState) {
            if ((this.ListarUsuariosOperationCompleted == null)) {
                this.ListarUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarUsuariosOperationCompleted);
            }
            this.InvokeAsync("ListarUsuarios", new object[] {
                        filtro}, this.ListarUsuariosOperationCompleted, userState);
        }
        
        private void OnListarUsuariosOperationCompleted(object arg) {
            if ((this.ListarUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarUsuariosCompleted(this, new ListarUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Agendamento {
        
        private int cdAgendamentoField;
        
        private System.DateTime dtConsultaField;
        
        private System.DateTime hrConsultaField;
        
        private Paciente pacienteField;
        
        private Prestador prestadorField;
        
        private Usuario usuarioField;
        
        /// <remarks/>
        public int CdAgendamento {
            get {
                return this.cdAgendamentoField;
            }
            set {
                this.cdAgendamentoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtConsulta {
            get {
                return this.dtConsultaField;
            }
            set {
                this.dtConsultaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime HrConsulta {
            get {
                return this.hrConsultaField;
            }
            set {
                this.hrConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Paciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Prestador Prestador {
            get {
                return this.prestadorField;
            }
            set {
                this.prestadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Paciente {
        
        private string bairroField;
        
        private int cdPacienteField;
        
        private string cidadeField;
        
        private string cpfField;
        
        private System.DateTime dtNascimentoField;
        
        private string emailField;
        
        private string enderecoField;
        
        private string estadoField;
        
        private string nmMaeField;
        
        private string nmPacienteField;
        
        private string nmPaiField;
        
        private string nmSocialField;
        
        private string rgField;
        
        private string telefoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public int CdPaciente {
            get {
                return this.cdPacienteField;
            }
            set {
                this.cdPacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtNascimento {
            get {
                return this.dtNascimentoField;
            }
            set {
                this.dtNascimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NmMae {
            get {
                return this.nmMaeField;
            }
            set {
                this.nmMaeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NmPaciente {
            get {
                return this.nmPacienteField;
            }
            set {
                this.nmPacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NmPai {
            get {
                return this.nmPaiField;
            }
            set {
                this.nmPaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NmSocial {
            get {
                return this.nmSocialField;
            }
            set {
                this.nmSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Rg {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class TipoConsulta {
        
        private int cdConsultaField;
        
        private string nmConsultaField;
        
        private string snAtivoField;
        
        /// <remarks/>
        public int CdConsulta {
            get {
                return this.cdConsultaField;
            }
            set {
                this.cdConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NmConsulta {
            get {
                return this.nmConsultaField;
            }
            set {
                this.nmConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SnAtivo {
            get {
                return this.snAtivoField;
            }
            set {
                this.snAtivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Convenio {
        
        private int cdConvenioField;
        
        private string nmConvenioField;
        
        private string snAtivoField;
        
        /// <remarks/>
        public int CdConvenio {
            get {
                return this.cdConvenioField;
            }
            set {
                this.cdConvenioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NmConvenio {
            get {
                return this.nmConvenioField;
            }
            set {
                this.nmConvenioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SnAtivo {
            get {
                return this.snAtivoField;
            }
            set {
                this.snAtivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Procedimento {
        
        private string cdProcedimentoField;
        
        private Convenio convenioField;
        
        private string nmProcedimentoField;
        
        private string snAtivoField;
        
        private double valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CdProcedimento {
            get {
                return this.cdProcedimentoField;
            }
            set {
                this.cdProcedimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Convenio Convenio {
            get {
                return this.convenioField;
            }
            set {
                this.convenioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NmProcedimento {
            get {
                return this.nmProcedimentoField;
            }
            set {
                this.nmProcedimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SnAtivo {
            get {
                return this.snAtivoField;
            }
            set {
                this.snAtivoField = value;
            }
        }
        
        /// <remarks/>
        public double Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Atendimento {
        
        private Agendamento agendamentoField;
        
        private int cdAtendimentoField;
        
        private System.DateTime dtAtendFinalizadoField;
        
        private System.DateTime dtAtendimentoField;
        
        private Prestador prestadorField;
        
        private Procedimento procedimentoField;
        
        private TipoConsulta tipoConsultaField;
        
        private Usuario usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Agendamento Agendamento {
            get {
                return this.agendamentoField;
            }
            set {
                this.agendamentoField = value;
            }
        }
        
        /// <remarks/>
        public int CdAtendimento {
            get {
                return this.cdAtendimentoField;
            }
            set {
                this.cdAtendimentoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtAtendFinalizado {
            get {
                return this.dtAtendFinalizadoField;
            }
            set {
                this.dtAtendFinalizadoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtAtendimento {
            get {
                return this.dtAtendimentoField;
            }
            set {
                this.dtAtendimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Prestador Prestador {
            get {
                return this.prestadorField;
            }
            set {
                this.prestadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Procedimento Procedimento {
            get {
                return this.procedimentoField;
            }
            set {
                this.procedimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TipoConsulta TipoConsulta {
            get {
                return this.tipoConsultaField;
            }
            set {
                this.tipoConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Prestador {
        
        private int cdPrestadorField;
        
        private string cpfField;
        
        private string nmPrestadorField;
        
        private string nrConselhoField;
        
        private string snAtivoField;
        
        private string telefoneField;
        
        /// <remarks/>
        public int CdPrestador {
            get {
                return this.cdPrestadorField;
            }
            set {
                this.cdPrestadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NmPrestador {
            get {
                return this.nmPrestadorField;
            }
            set {
                this.nmPrestadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NrConselho {
            get {
                return this.nrConselhoField;
            }
            set {
                this.nrConselhoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SnAtivo {
            get {
                return this.snAtivoField;
            }
            set {
                this.snAtivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Usuario {
        
        private string nomeField;
        
        private string senhaField;
        
        private string snAtivoField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SnAtivo {
            get {
                return this.snAtivoField;
            }
            set {
                this.snAtivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AgendarAgendamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RemarcarAgendamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ExcluirAgendamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListaAgendamentosCompletedEventHandler(object sender, ListaAgendamentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaAgendamentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaAgendamentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Agendamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Agendamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GerarAtendimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ExcluirAtendimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AtualizarAtendimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListarAtendimentosCompletedEventHandler(object sender, ListarAtendimentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAtendimentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAtendimentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Atendimento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Atendimento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CadastrarConvenioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InativarConvenioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListarConveniosCompletedEventHandler(object sender, ListarConveniosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarConveniosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarConveniosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Convenio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Convenio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CadastrarPacienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AlterarPacienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListaPacienteCompletedEventHandler(object sender, ListaPacienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Paciente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Paciente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CadastrarPrestadorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InativarPrestadorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AtualizarPrestadorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListaPrestadoresCompletedEventHandler(object sender, ListaPrestadoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaPrestadoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaPrestadoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Prestador[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Prestador[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AdicionarProcedimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AtuaizarProcedimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListarProcedimentoCompletedEventHandler(object sender, ListarProcedimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarProcedimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarProcedimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Procedimento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Procedimento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InserirTipoConsultaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InativarTipoConsultaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListarTipoConsultaCompletedEventHandler(object sender, ListarTipoConsultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTipoConsultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTipoConsultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoConsulta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoConsulta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CadastrarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AlterarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListarUsuariosCompletedEventHandler(object sender, ListarUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591